### ISSUE TITLE
Clearify what this modules does in readme

### ISSUE THREAD

**Issue by drts01** [rhinstaller/pocketlint#35]
It is not immediately clear what this module does without diving into the source code.

**Comment by jkonecny12** [comment]
Hello, thank you for your issue.

This module is basically wrapper around Pylint, however, pylint project moved a lot in a performance so enhancements this project is doing are not required anymore. This project is most probably going to be deprecated in future because it does not have much benefit over using Pylint directly and it has a big drawback in a performance.
